export enum ReportType {
  INBOUND_DETAIL = 'INBOUND_DETAIL',
  OUTBOUND_DETAIL = 'OUTBOUND_DETAIL',
  INVENTORY_DETAIL = 'INVENTORY_DETAIL',
  EXCEPTION_DETAIL = 'EXCEPTION_DETAIL',
  CUSTOMER_CHANGE_LOG = 'CUSTOMER_CHANGE_LOG',
  AUDIT_LOG = 'AUDIT_LOG',
}
