ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OUTBOUND_BOX_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OUTBOUND_BOX_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OUTBOUND_BOX_ITEM_ADD';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OUTBOUND_BOX_ITEM_REMOVE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OUTBOUND_BOX_ITEM_CLEAR';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OUTBOUND_BOX_REOPEN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OUTBOUND_BOX_DELETE';

ALTER TABLE "outbound_boxes"
  ADD COLUMN "boxName" TEXT,
  ADD COLUMN "sizePreset" TEXT,
  ADD COLUMN "customSize" TEXT,
  ADD COLUMN "weightLb" DOUBLE PRECISION;
