ALTER TYPE "ExceptionType" RENAME VALUE 'UPC_NOT_FOUND' TO 'UPC_NOT_MATCHED';
ALTER TYPE "ExceptionType" RENAME VALUE 'CUSTOMER_MISMATCH' TO 'CUSTOMER_OWNERSHIP_MISMATCH';
ALTER TYPE "ExceptionType" RENAME VALUE 'IMEI_NOT_IN_STOCK' TO 'IMEI_NOT_INBOUNDED';
