export enum ExceptionType {
  UPC_NOT_FOUND = 'UPC_NOT_FOUND',
  IMEI_DUPLICATED = 'IMEI_DUPLICATED',
  UPS_DUPLICATED = 'UPS_DUPLICATED',
  CUSTOMER_MISMATCH = 'CUSTOMER_MISMATCH',
  IMEI_NOT_IN_STOCK = 'IMEI_NOT_IN_STOCK',
}
