export enum ExceptionType {
  UPC_NOT_MATCHED = 'UPC_NOT_MATCHED',
  IMEI_DUPLICATED = 'IMEI_DUPLICATED',
  UPS_DUPLICATED = 'UPS_DUPLICATED',
  CUSTOMER_OWNERSHIP_MISMATCH = 'CUSTOMER_OWNERSHIP_MISMATCH',
  IMEI_NOT_INBOUNDED = 'IMEI_NOT_INBOUNDED',
}
